### ISSUE TITLE
Incoming messages overwritten

### ISSUE THREAD

**Issue by twobitfool** [actionhero/actionhero-chat#220]
With each new message, the `incomingMessages` reverts back to an empty array, presumably because `handleMessage` is being called by `useChatStream`. 

Notice that `handleMessage` works fine when called directly (with a fake message).

Probably related to [this react hooks "feature"](https://github.com/facebook/react/issues/14066), when a `useState` value is referenced inside a `useEffect` callback.

![glitch](https://user-images.githubusercontent.com/12453/123522680-cbecee80-d68c-11eb-8bed-477f517fd18d.gif)

**Comment by evantahler** [comment]
Thanks for finding this!  

Are you interested in contributing a fix?

**Comment by twobitfool** [comment]
No thanks. This kind of spooky behavior is one of the many reasons that I won't go near React hooks 😜

**Comment by evantahler** [comment]
Fair enough - https://github.com/actionhero/actionhero-chat/commit/633cc0ade13d232f7ee9c5ae5295a4cea4b84886 has the fix
