### ISSUE TITLE
Chrome doesn't render index page while Edge does so beautifully.

### ISSUE THREAD

**Issue by krlicmuhamed** [actionhero/actionhero-chat#33]
I can't figure this out next.js should render the page for chrome as for edge the same. However, chrome doesn't render the index page as it should.
[Chrome](https://imgur.com/YPh3tZ3)
Here's the same url path for edge 
[Edge](https://imgur.com/8S4L8rP)
this is the one that is working well.
Is there a clear reason why this is happening?

**Comment by evantahler** [comment]
@krlicmuhamed can you let us know what happens when you visit https://chat.actionherojs.com (where this app is deployed?). This will ensure that there isn't a problem with your local setup first.

**Comment by evantahler** [comment]
Here's a render test from Browser Stack showing that things look good in IE 9, Edge, etc. 

https://www.browserstack.com/screenshots/0ec5743b75763c8e99b2d938ad6ff7e9a9c9668f

**Comment by krlicmuhamed** [comment]
Something's against the localhost chrome setup... I still get the same basic public index file rendered instead of next.js, chat.actionherojs.com works fine on chrome

**Comment by evantahler** [comment]
I'm going to close this issues then.  Please open a new issue if you can find a way to reproduce the issue. 

Some debugging ideas for you:
- test in incognito chrome
- rest with all extensions disabled
- test forwarding localhost to another machine (using a tool like ngrok) to try another install of chrome
